# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\ZKFLproject\pyqt\pyqt5_crawler\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 706)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setStyleSheet("QGroupBox{border:none}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.treeWidget, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 9)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.line_url = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_url.setObjectName("line_url")
        self.gridLayout_3.addWidget(self.line_url, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(95, 0))
        self.groupBox.setStyleSheet("QGroupBox{border:none}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.groupBox, 0, 2, 6, 1)
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.line_xpath = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_xpath.setText("")
        self.line_xpath.setObjectName("line_xpath")
        self.gridLayout_3.addWidget(self.line_xpath, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.line_headerskey = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_headerskey.setObjectName("line_headerskey")
        self.gridLayout_3.addWidget(self.line_headerskey, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.line_headersvalue = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_headersvalue.setObjectName("line_headersvalue")
        self.gridLayout_3.addWidget(self.line_headersvalue, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.line_path = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_path.setObjectName("line_path")
        self.gridLayout_3.addWidget(self.line_path, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.line_name = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_name.setObjectName("line_name")
        self.gridLayout_3.addWidget(self.line_name, 5, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setStyleSheet("QGroupBox{border:none}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 6, 0, 1, 3)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "当前url"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "状态"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "console"))
        self.label.setText(_translate("MainWindow", "url"))
        self.comboBox.setItemText(1, _translate("MainWindow", "picture"))
        self.comboBox.setItemText(2, _translate("MainWindow", "video"))
        self.comboBox.setItemText(3, _translate("MainWindow", "music"))
        self.comboBox.setItemText(4, _translate("MainWindow", "m3u8"))
        self.label_7.setText(_translate("MainWindow", "format:"))
        self.pushButton_5.setText(_translate("MainWindow", "m3u8"))
        self.label_6.setText(_translate("MainWindow", "xpath"))
        self.label_2.setText(_translate("MainWindow", "headers_key"))
        self.label_3.setText(_translate("MainWindow", "headers_valeu"))
        self.label_5.setText(_translate("MainWindow", "path"))
        self.label_4.setText(_translate("MainWindow", "name"))
        self.pushButton_4.setText(_translate("MainWindow", "添加Xpath"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        self.pushButton_3.setText(_translate("MainWindow", "下载路径"))
        self.pushButton_2.setText(_translate("MainWindow", "添加请求头"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

